 # Generated by Django 5.0.6 on 2024-06-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_name_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_address',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
